// <auto-generated />
using HotelService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240306191104_initials")]
    partial class initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelService.Domain.Models.ContactModel", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("HotelUUID")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UUID");

                    b.HasIndex("HotelUUID");

                    b.ToTable("ContactModels");
                });

            modelBuilder.Entity("HotelService.Domain.Models.HotelModel", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<string>("AuthorizedPersonFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorizedPersonLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UUID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelService.Domain.Models.ReportDetail", b =>
                {
                    b.Property<int>("ReportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportRequestId"), 1L, 1);

                    b.Property<int>("HotelCount")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberCount")
                        .HasColumnType("int");

                    b.Property<int>("ReportRequestUUID")
                        .HasColumnType("int");

                    b.Property<int>("UUID")
                        .HasColumnType("int");

                    b.HasKey("ReportRequestId");

                    b.HasIndex("ReportRequestUUID");

                    b.ToTable("ReportDetails");
                });

            modelBuilder.Entity("HotelService.Domain.Models.ReportRequest", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UUID");

                    b.ToTable("ReportRequests");
                });

            modelBuilder.Entity("HotelService.Domain.Models.ContactModel", b =>
                {
                    b.HasOne("HotelService.Domain.Models.HotelModel", "Hotel")
                        .WithMany("Contacts")
                        .HasForeignKey("HotelUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelService.Domain.Models.ReportDetail", b =>
                {
                    b.HasOne("HotelService.Domain.Models.ReportRequest", "ReportRequest")
                        .WithMany()
                        .HasForeignKey("ReportRequestUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportRequest");
                });

            modelBuilder.Entity("HotelService.Domain.Models.HotelModel", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
